### ISSUE TITLE
vanity imports and go-gettability

### ISSUE THREAD

**Issue by mmikulicic** [dimonomid/geekmarks#2]
hi dima, nice tool!

Please consider using canonical imports and make your tool go-gettable:

https://texlution.com/post/golang-canonical-import-paths/
https://golang.org/doc/go1.4#canonicalimports

**Comment by dimonomid** [comment]
Hi Marko, thank you for pointing that out! I'll surely fix it.

**Comment by dimonomid** [comment]
Resolved by https://github.com/dimonomid/geekmarks/commit/2bcfb6c48069431f60c4b151828324775021429f
