### ISSUE TITLE
Hardcoded server / serverSSL chrome extension

### ISSUE THREAD

**Issue by mariusrugan** [dimonomid/geekmarks#6]
Hi,

geekmarks.dmitryfrank.com is hardcoded in chrome extension's options.js; gmclient.js

**Comment by dimonomid** [comment]
There's nothing wrong with this: these are default values.

`options.js` is specific to Chrome extension, and `gmclient.js` is a generic client which can be used in any JS-enabled environment (web UI, node.js, React Native, etc).

You can easily override this value in the extension's options.
